const AI_MAX_BODY_SIZE = process.env.AI_MAX_BODY_SIZE || '100kb';
const AI_MAX_MESSAGE_LENGTH = Number(process.env.AI_MAX_MESSAGE_LENGTH || 4000);
const AI_MAX_DESCRIPTION_LENGTH = Number(process.env.AI_MAX_DESCRIPTION_LENGTH || 5000);
const AI_MAX_HISTORY_MESSAGES = Number(process.env.AI_MAX_HISTORY_MESSAGES || 20);
const AI_MAX_HISTORY_MESSAGE_LENGTH = Number(
    process.env.AI_MAX_HISTORY_MESSAGE_LENGTH || 4000
);

module.exports = {
    AI_MAX_BODY_SIZE,
    AI_MAX_MESSAGE_LENGTH,
    AI_MAX_DESCRIPTION_LENGTH,
    AI_MAX_HISTORY_MESSAGES,
    AI_MAX_HISTORY_MESSAGE_LENGTH
};
