import React from "react";

/**
 * Exact IDs of the legacy dummy/fixture complaints previously generated by the application.
 * Only these exact IDs are removed during cleanup.
 */
export const LEGACY_FIXTURE_IDS = new Set([
    "mock-1",
    "mock-2",
    "mock-3",
    "CMP-M1",
    "CMP-M2",
    "CMP-M3",
]);

/**
 * Check if a complaint matches one of the exact legacy fixture IDs.
 * Note: Never match generic prefixes (such as "CMP-M") or place/type/department
 * combinations, as doing so could delete legitimate citizen reports.
 */
export const isDummyReport = (r) => {
    if (!r || typeof r !== "object") return false;
    const id = r.id != null ? String(r.id) : "";
    const complaintId = r.complaint_id != null ? String(r.complaint_id) : "";
    return LEGACY_FIXTURE_IDS.has(id) || LEGACY_FIXTURE_IDS.has(complaintId);
};

/**
 * Remove legacy dummy fixtures from storage (localStorage) if present.
 * Does not remove legitimate user reports.
 */
export const cleanLegacyFixtures = (storage) => {
    if (!storage || typeof storage.getItem !== "function") return;
    const keys = ["reports", "civicfix_issues"];
    keys.forEach((key) => {
        try {
            const raw = storage.getItem(key);
            if (!raw) return;
            const parsed = JSON.parse(raw);
            if (Array.isArray(parsed) && parsed.some(isDummyReport)) {
                const cleaned = parsed.filter((r) => !isDummyReport(r));
                if (cleaned.length > 0) {
                    storage.setItem(key, JSON.stringify(cleaned));
                } else {
                    storage.removeItem(key);
                }
            }
        } catch {
            // Ignore parse errors
        }
    });
};

/**
 * Merge and normalize legitimate reports from API and local storage.
 * Only exact legacy dummy fixtures are excluded.
 */
export const processReports = (apiReports = [], localReports = []) => {
    const validLocalReports = (Array.isArray(localReports) ? localReports : []).filter(
        (r) => !isDummyReport(r)
    );
    const validApiReports = (Array.isArray(apiReports) ? apiReports : []).filter(
        (r) => !isDummyReport(r)
    );

    // Merge reports, avoiding duplicates by complaint_id or id
    const merged = [...validApiReports];
    const apiIds = new Set(validApiReports.map((r) => r.complaint_id || r.id));

    validLocalReports.forEach((r) => {
        const id = r.complaint_id || r.id;
        if (id && !apiIds.has(id)) {
            merged.push(r);
        }
    });

    // Normalize property names
    return merged
        .map((r) => ({
            ...r,
            lat: r.latitude || r.lat,
            lng: r.longitude || r.lng,
            issueType: r.issue_type || r.issueType || "Unknown",
            place: r.area ? `${r.area}, ${r.city}` : (r.place || "Unknown"),
            severity: r.severity || "Low",
            status: r.status || "Pending",
            date: r.created_at ? new Date(r.created_at).toLocaleDateString() : (r.date || "Today"),
        }))
        .filter((r) => r.lat && r.lng);
};

/**
 * Fetch complaints from the backend API, clean legacy storage fixtures,
 * read available local reports, and return processed reports and error state.
 */
export const fetchMapReports = async ({ apiBase, fetchFn = fetch, storage = null }) => {
    let apiReports = [];
    let apiError = null;

    try {
        const res = await fetchFn(`${apiBase}/complaints`);
        const data = await res.json();
        if (res.ok) {
            apiReports = data.data || [];
            apiError = null;
        } else {
            apiError = data?.error?.message || "Failed to load complaints. Please try again.";
        }
    } catch (err) {
        console.error("Failed to fetch reports from API:", err);
        apiError = "Failed to load complaints. Please try again.";
    }

    if (storage) {
        cleanLegacyFixtures(storage);
    }

    let localReports = [];
    if (storage && typeof storage.getItem === "function") {
        try {
            const raw = storage.getItem("reports");
            if (raw) {
                const parsed = JSON.parse(raw);
                if (Array.isArray(parsed)) {
                    localReports = parsed;
                }
            }
        } catch (err) {
            console.error("Failed to parse reports from localStorage:", err);
        }
    }

    const reports = processReports(apiReports, localReports);

    return {
        apiReports,
        apiError,
        reports,
    };
};

/**
 * Notice banner component displayed above the map for loading, empty, and error states.
 */
export const MapStatusNotice = ({ loading, apiError, reportsCount, onRetry }) => {
    if (loading) {
        return React.createElement(
            "div",
            {
                "data-testid": "map-loading-state",
                style: {
                    textAlign: "center",
                    padding: "8px 16px",
                    marginBottom: "10px",
                    color: "#666",
                    fontSize: "14px",
                    fontStyle: "italic",
                },
            },
            "⏳ Loading complaints..."
        );
    }

    if (apiError && reportsCount === 0) {
        return React.createElement(
            "div",
            {
                "data-testid": "map-error-state",
                style: {
                    textAlign: "center",
                    padding: "10px 16px",
                    marginBottom: "10px",
                    backgroundColor: "#fff3cd",
                    borderRadius: "8px",
                    border: "1px solid #ffeeba",
                    color: "#856404",
                    fontSize: "14px",
                    fontWeight: "500",
                },
            },
            React.createElement("span", null, `⚠️ ${apiError}`),
            onRetry &&
                React.createElement(
                    "button",
                    {
                        type: "button",
                        onClick: onRetry,
                        "data-testid": "map-retry-button",
                        style: {
                            marginLeft: "12px",
                            padding: "4px 10px",
                            borderRadius: "4px",
                            border: "1px solid #856404",
                            backgroundColor: "#fff",
                            color: "#856404",
                            cursor: "pointer",
                            fontSize: "12px",
                            fontWeight: "600",
                        },
                    },
                    "🔄 Retry"
                )
        );
    }

    if (reportsCount === 0) {
        return React.createElement(
            "div",
            {
                "data-testid": "map-empty-state",
                style: {
                    textAlign: "center",
                    padding: "10px 16px",
                    marginBottom: "10px",
                    backgroundColor: "#f8f9fa",
                    borderRadius: "8px",
                    border: "1px dashed #ced4da",
                    color: "#555",
                    fontSize: "14px",
                    fontWeight: "500",
                },
            },
            "ℹ️ No complaints reported yet. The map is currently clear."
        );
    }

    if (apiError && reportsCount > 0) {
        return React.createElement(
            "div",
            {
                "data-testid": "map-error-state",
                style: {
                    textAlign: "center",
                    padding: "6px 12px",
                    marginBottom: "10px",
                    backgroundColor: "#fff3cd",
                    borderRadius: "6px",
                    border: "1px solid #ffeeba",
                    color: "#856404",
                    fontSize: "12px",
                },
            },
            React.createElement("span", null, `⚠️ ${apiError} (showing saved offline reports)`),
            onRetry &&
                React.createElement(
                    "button",
                    {
                        type: "button",
                        onClick: onRetry,
                        "data-testid": "map-retry-button",
                        style: {
                            marginLeft: "8px",
                            padding: "2px 8px",
                            borderRadius: "4px",
                            border: "1px solid #856404",
                            backgroundColor: "#fff",
                            color: "#856404",
                            cursor: "pointer",
                            fontSize: "11px",
                            fontWeight: "600",
                        },
                    },
                    "🔄 Retry"
                )
        );
    }

    return null;
};
